# Generated by Django 5.1.1 on 2024-11-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_veiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.SmallIntegerField(choices=[(1, 'ETANOL'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'GASOLINA'), (5, 'GÁS NATURAL'), (6, 'ELÉTRICO'), (7, 'HÍBRIDO'), (8, 'NITROGÊNIO')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[(1, 'BRANCO'), (2, 'AMARELO'), (3, 'AZUL'), (4, 'PRATA'), (5, 'PRETO'), (6, 'VERMELHO'), (7, 'ROSA'), (8, 'ROXO'), (9, 'VERDE')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET - GM'), (4, 'FERRARI'), (5, 'FIAT'), (6, 'FORD'), (7, 'HONDA'), (8, 'HYUNDAI'), (9, 'VOLKSWAGEN'), (10, 'MERCEDES-BENZ')]),
        ),
    ]
